### ISSUE TITLE
smol yuri is a white rectangle

### ISSUE THREAD

**Issue by wireframe-flop** [KittyMcTophat/paper-smol-yuri#1]
![image](https://user-images.githubusercontent.com/111504982/185381056-00b5ca53-1ca2-4939-8c9d-4847919f9b44.png)

**Comment by KittyMcTophat** [comment]
I have a couple questions.
- Does the issue persist if you restart the game?
- Are your graphics drivers up to date?

Also if you go to the folder C:/Users/[Your user name]/AppData/Roaming/Godot/app_userdata/Paper Smol Yuri/logs you should see a file named "godot.log" can you send that to me so that I have more information on the issue?

**Comment by wireframe-flop** [comment]
nvm my graphics driver was old

**Comment by KittyMcTophat** [comment]
alright, cool
glad i could help
